// Tüm müfredat verisi — admin paneli için merkezi kaynak

export interface LessonHint {
  title: string;
  words: string[];
}

export interface UnitData {
  id: string;
  levelId: string;
  order: number;
  title: string;
  description: string;
  icon: string;
  city: string;
  culturalHint: string;
  lessons: LessonHint[];
}

export interface LevelData {
  id: string;
  order: number;
  title: string;
  description: string;
}

export const LEVELS: LevelData[] = [
  { id: 'level1', order: 1, title: 'Destpêkê (A1)', description: 'Kurmanciya bingehîn' },
  { id: 'level2', order: 2, title: 'Bingehîn (A2)', description: 'Axaftinên rojane' },
  { id: 'level3', order: 3, title: 'Navîn (B1)', description: 'Avahiyên hevokê' },
  { id: 'level4', order: 4, title: 'Navîn-Pêşketî (B2)', description: 'Rêziman û nivîsandin' },
  { id: 'level5', order: 5, title: 'Pêşketî (C1)', description: 'Axaftina herikbar' },
  { id: 'level6', order: 6, title: 'Pispor (C2)', description: 'Astê zimanê dayikê' },
];

export const UNITS: UnitData[] = [
  // ─── SEVİYE 1 — A1 ───
  {
    id: 'unit1', levelId: 'level1', order: 1,
    title: 'Silavdan', description: 'Selamlama ve temel ifadeler', icon: '👋',
    city: 'Amed (Diyarbakır) — Sur içi, tarihi surlar',
    culturalHint: 'Baran, İstanbul\'dan Amed\'e yeni geldi. Berfin onu Sur\'un tarihi kapısında karşılıyor.',
    lessons: [
      { title: 'Silavên Bingehîn', words: ['silav', 'spas', 'belê', 'na', 'rojbaş', 'şevbaş', 'roj', 'şev'] },
      { title: 'Tu çawa yî?', words: ['tu çawa yî', 'ez baş im', 'nexweş', 'ez', 'tu', 'ew', 'baş', 'spas'] },
      { title: 'Nav û nasname', words: ['nav', 'ez ... im', 'tu kî yî', 'ev', 'ew', 'kî', 'çi', 'ku'] },
      { title: 'Xatirê te', words: ['xatirê te', 'oxir be', 'bi xêr be', 'xweşî bimîne', 'şevbaş', 'rojbaş', 'êvarbaş', 'sibehbaş'] },
      { title: 'Ji ku yî?', words: ['ji ku yî', 'ez ji ... im', 'welat', 'bajar', 'Kurdistan', 'Tirkiye', 'Sûriye', 'gund'] },
    ],
  },
  {
    id: 'unit2', levelId: 'level1', order: 2,
    title: 'Jimare', description: 'Sayılar 1-20 ve alışveriş', icon: '🔢',
    city: 'Van — Akdamar Adası ve Van gölü kıyısı',
    culturalHint: 'Baran ilk kez Van gölünü görüyor. Berfin teknede Kürtçe saymayı öğretiyor.',
    lessons: [
      { title: 'Jimarên 1-5', words: ['yek', 'du', 'sê', 'çar', 'pênc', 'jimar', 'tişt', 'yek bi yek'] },
      { title: 'Jimarên 6-10', words: ['şeş', 'heft', 'heşt', 'neh', 'deh', 'roj', 'hefte', 'tamam'] },
      { title: 'Çend', words: ['çend', 'çend ... hene', 'kes', 'sêv', 'pirtûk', 'qelem', 'hemî', 'tenê'] },
      { title: 'Min ... Heye', words: ['min ... heye', 'min ... hene', 'kûr', 'keç', 'sêv', 'pirtûk', 'qelem', 'top'] },
      { title: 'Diyalogên Jimarê', words: ['tu çend salî yî', 'ez ... salî me', 'jimara telefonê', 'hêdî', 'dîsa', 'malbat', 'sal', 'belê'] },
    ],
  },
  {
    id: 'unit3', levelId: 'level1', order: 3,
    title: 'Reng', description: 'Renkler', icon: '🎨',
    city: 'Mardin — Tarihi taş evler ve çarşı',
    culturalHint: 'Berfin Baran\'a Mardin\'in renkli bazarında Newroz kıyafetlerini gösteriyor.',
    lessons: [
      { title: 'Rengên Bingehîn 1', words: ['sor', 'şîn', 'kesk', 'zer', 'spî', 'reng', 'ev ... e', 'xweş'] },
      { title: 'Rengên Bingehîn 2', words: ['reş', 'binefşî', 'narincî', 'qehweyî', 'pembe', 'tarî', 'zelal', 'şev'] },
      { title: 'Reng Di Hevokê De', words: ['rengê ... çi ye', 'ezman', 'giya', 'berf', 'roj', 'ereb', 'çav', 'kinc'] },
      { title: 'Rengên Tiştan', words: ['erebeya sor', 'kincê reş', 'gula sor', 'çûkê zer', 'berfa spî', 'darê kesk', 'min ... heye', 'hez dikim'] },
      { title: 'Diyalogên Rengan', words: ['çi rengî', 'dixwazim', 'jî', 'ezman', 'giya', 'xwîn', 'belê', 'na'] },
    ],
  },
  {
    id: 'unit4', levelId: 'level1', order: 4,
    title: 'Malbat', description: 'Aile üyeleri', icon: '👨‍👩‍👧',
    city: 'İstanbul — Tarlabaşı ve Bağcılar Kürt mahallesi',
    culturalHint: 'Baran İstanbul\'daki dayısının evinde büyük Kürt ailesini Berfin\'e telefonda anlatıyor.',
    lessons: [
      { title: 'Malbata Bingehîn', words: ['malbat', 'dê', 'dayik', 'bav', 'bira', 'xwişk', 'zarok', 'kes'] },
      { title: 'Malbata Mezin', words: ['ap', 'xal', 'met', 'xaltî', 'bapîr', 'mêmê', 'pîr', 'ciwan'] },
      { title: 'Bavê Min û Diya Min', words: ['bavê min', 'diya min', 'biraya min', 'xwişka min', 'mamoste', 'li malê', 'heye', 'tune'] },
      { title: 'Navê Wî Çi Ye', words: ['nav', 'navê wî', 'navê wê', 'ev ... e', 'ev ... ye', 'hesen', 'fatma', 'çi ye'] },
      { title: 'Diyalogên Malbatê', words: ['çend kes e', 'li ku dijî', 'dijî', 'li bajêr', 'li gundê', 'belê', 'na', 'û'] },
    ],
  },
  {
    id: 'unit5', levelId: 'level1', order: 5,
    title: 'Xwarin', description: 'Yiyecek ve içecekler', icon: '🍎',
    city: 'Doğubayazıt — İshakpaşa Sarayı ve Ağrı Dağı eteği',
    culturalHint: 'Baran ve Berfin İshakpaşa Sarayı\'nın bahçesinde geleneksel Kürt yemeklerini paylaşıyor.',
    lessons: [
      { title: 'Xwarinên Bingehîn', words: ['nan', 'goşt', 'sêv', 'moz', 'tirî', 'pirinc', 'nîsk', 'xwarin'] },
      { title: 'Vexwarin', words: ['av', 'çay', 'şîr', 'mast', 'qehwe', 'şerbet', 'vexwarin', 'vedixwim'] },
      { title: 'Ez Dixwazim', words: ['dixwazim', 'nadixwazim', 'germ', 'sar', 'xweş', 'xerab', 'zêde', 'hinek'] },
      { title: 'Xwarina Rojane', words: ['taştê', 'nîvro', 'şîv', 'birçî', 'têr', 'amade', 'dixwim', 'vedixwim'] },
      { title: 'Diyalogên Xwarinê', words: ['xwaringeh', 'menû', 'baha', 'çi ye', 'spas', 'noş', 'bide min', 'ji kerema xwe'] },
    ],
  },
  {
    id: 'unit6', levelId: 'level1', order: 6,
    title: 'Ajal', description: 'Hayvanlar', icon: '🐾',
    city: 'Van — Van Kalesi, Van gölü kıyısı ve Van çarşısı',
    culturalHint: 'Kurdo dede Van Kalesi\'nin gölgesinde Baran\'a Kurt kedisi ve köy hayvanlarını gösteriyor.',
    lessons: [
      { title: 'Ajalên Malê', words: ['pisîk', 'kûçik', 'hesp', 'çûk', 'masî', 'ker', 'mirîşk', 'ajal'] },
      { title: 'Ajalên Kovî', words: ['şêr', 'gur', 'rovî', 'hirç', 'mar', 'fil', 'kêzik', 'kovî'] },
      { title: 'Ajal Çawa Ye', words: ['mezin', 'piçûk', 'bilez', 'hêdî', 'xweş', 'tirsnak', 'dilsoz', 'nazik'] },
      { title: 'Reng û Ajal', words: ['spî', 'reş', 'sor', 'zer', 'kesk', 'pisîka spî', 'kûçikê reş', 'çûkê zer'] },
      { title: 'Diyalogên Ajalan', words: ['heye', 'tune', 'ji ... hez dikim', 'çi ajal', 'li ku ye', 'li malê', 'li derve', 'biçûk'] },
    ],
  },
  {
    id: 'unit7', levelId: 'level1', order: 7,
    title: 'Lêker', description: 'Temel fiiller', icon: '🏃',
    city: 'Hakkari — Cilo dağları ve Zap vadisi',
    culturalHint: 'Baran Hakkari\'de aşiret düğününde çeşitli faaliyetleri Kürtçe anlatmayı öğreniyor.',
    lessons: [
      { title: 'Lekerên Bingehîn', words: ['çûn', 'hatin', 'xwarin', 'vexwarin', 'xwendin', 'nivîsîn', 'rûniştin', 'rabûn'] },
      { title: 'Ez Diçim', words: ['ez', 'tu', 'ew', 'em', 'diçim', 'tê', 'dixwînim', 'dinivîsim'] },
      { title: 'Li Malê û Dibistanê', words: ['li malê', 'li dibistanê', 'li ser maseyê', 'rûdinim', 'dixwînim', 'dinivîsim', 'dixwim', 'têm'] },
      { title: 'Pirsa Bi Lekeran', words: ['ma', 'çi', 'ku', 'kengê', 'ma tu diçî?', 'çi dikî?', 'ku diçî?', 'erê'] },
      { title: 'Diyalogên Rojane', words: ['sibehê', 'naha', 'paşê', 'vedigerim', 'dibim', 'dixebitim', 'dilisim', 'axivim'] },
    ],
  },
  {
    id: 'unit8', levelId: 'level1', order: 8,
    title: 'Rengdêr', description: 'Sıfatlar', icon: '✨',
    city: 'Şanlıurfa — Balıklıgöl ve Harran ovası',
    culturalHint: 'Baran Balıklıgöl\'de Berfin\'e Urfa\'nın tarihi yapılarını sıfatlarla anlatıyor.',
    lessons: [
      { title: 'Rengdêrên Bingehîn', words: ['mezin', 'piçûk', 'nû', 'kevin', 'xweş', 'xerab', 'giran', 'sivik'] },
      { title: 'Mezin û Piçûk', words: ['dirêj', 'kurt', 'qelew', 'zirav', 'mezin', 'piçûk', 'hesp', 'ker'] },
      { title: 'Rengdêr Di Hevokê De', words: ['pirtûka nû', 'malê mezin', 'qelemê kevin', 'avê sar', 'çaya germ', 'xwarinê xweş', 'zarokê piçûk', 'pirtûk'] },
      { title: 'Germ û Sar', words: ['germ', 'sar', 'bilez', 'hêdî', 'av', 'çay', 'hesp', 'ker'] },
      { title: 'Diyalogên Rengdêrî', words: ['jîr', 'xemgîn', 'bextewar', 'westiyayî', 'sax', 'nexweş', 'baş e', 'ne baş e'] },
    ],
  },
  {
    id: 'unit9', levelId: 'level1', order: 9,
    title: 'Dem', description: 'Zaman ve günler', icon: '⏰',
    city: 'Bitlis — Bitlis kalesi ve Tatvan iskelesi',
    culturalHint: 'Baran Tatvan iskelesinde Berfin ile buluşma vakti ayarlıyor, saat sormayı öğreniyor.',
    lessons: [
      { title: 'Demên Rojê', words: ['sibeh', 'nîvro', 'êvar', 'şev', 'roj', 'îro', 'zû', 'dereng'] },
      { title: 'Rojên Hefteyê', words: ['duşem', 'sêşem', 'çarşem', 'pêncşem', 'înî', 'şemî', 'yekşem', 'hefte'] },
      { title: 'Saet Çend E', words: ['saet', 'saet çend e?', 'yek', 'du', 'sê', 'çar', 'nîv', 'deqîqe'] },
      { title: 'Duh, Îro, Sibê', words: ['duh', 'îro', 'sibê', 'niha', 'paşê', 'berê', 'her roj', 'carinan'] },
      { title: 'Diyalogên Demê', words: ['kengê', 'di saet ... de', 'di sibehê de', 'di êvarê de', 'betlane', 'hevdîtin', 'were', 'paşê'] },
    ],
  },
  {
    id: 'unit10', levelId: 'level1', order: 10,
    title: 'Cih', description: 'Mekanlar ve yönler', icon: '📍',
    city: 'Siirt — Botan vadisi ve tarihi Siirt çarşısı',
    culturalHint: 'Baran Siirt\'in dar sokaklarında kayboldu, Berfin telefonda yol tarifi veriyor.',
    lessons: [
      { title: 'Cihên Bingehîn', words: ['mal', 'dibistan', 'bazar', 'park', 'bajar', 'gund', 'nexweşxane', 'mizgeft'] },
      { title: 'Li Ku Ye', words: ['li ku ye?', 'li ku yî?', 'li vir', 'li wir', 'vir', 'wir', 'derî', 'otêl'] },
      { title: 'Ez Diçim', words: ['diçim', 'diçî', 'diçe', 'diçin', 'malê', 'dibistanê', 'bazarê', 'parkê'] },
      { title: 'Nêzîk û Dûr', words: ['nêzîk', 'dûr', 'ji vir', 'rast', 'çep', 'rasterast', 'ber bi', 'rê'] },
      { title: 'Diyalogên Cihê', words: ['bibore', 'çawa diçim?', 'li kêleka', 'pişt', 'ber', 'nêzî', 'were', 'here'] },
    ],
  },

  // ─── SEVİYE 2 — A2 ───
  {
    id: 'unit11', levelId: 'level2', order: 11,
    title: 'Bedenê mirov', description: 'Vücut ve sağlık', icon: '🏥',
    city: 'Muş — Muş ovası ve Varto ilçesi',
    culturalHint: 'Baran Muş\'ta rahatsızlanıyor, köy kliniğinde doktora semptomlarını Kürtçe anlatmaya çalışıyor.',
    lessons: [
      { title: 'Ez Dixwazim', words: ['ez dixwazim', 'ez naxwazim', 'tu dixwazî', 'ew dixwaze', 'av', 'çay', 'kofî', 'nan'] },
      { title: 'Ev Çi Ye', words: ['ev çi ye?', 'ev ... e', 'kitêb', 'qelem', 'mase', 'kursî', 'derî', 'pencere'] },
      { title: 'Nasname û Tanıştin', words: ['navê te çi ye?', 'navê min ... e', 'tu ji ku yî?', 'ez ji ... me', 'tu çi dikî?', 'xwendekar', 'mamoste', 'bijîşk'] },
      { title: 'Hevokên Hêsan', words: ['dixwîne', 'dinivîse', 'dibîne', 'dibêje', 'pirtûk', 'name', 'heval', 'bersiv'] },
      { title: 'Axaftinên Rojane', words: ['spas', 'xêr be', 'bibore', 'baş e', 'belê', 'na', 'niha', 'paşê'] },
    ],
  },
  {
    id: 'unit12', levelId: 'level2', order: 12,
    title: 'Kirîn û firotandinê', description: 'Alışveriş ve pazarlık', icon: '🛍️',
    city: 'Cizre — Cudi dağı eteği ve eski Cizre çarşısı',
    culturalHint: 'Berfin Baran\'a Cizre\'nin tarihi çarşısında Kürtçe pazarlık etmeyi öğretiyor.',
    lessons: [
      { title: 'Ez, Tu, Ew', words: ['diçim', 'diçî', 'diçe', 'têm', 'têyî', 'tê', 'dikim', 'dike'] },
      { title: 'Em, Hûn, Ew', words: ['diçin', 'tên', 'dikin', 'em', 'hûn', 'ew', 'dixwînin', 'diaxivin'] },
      { title: 'Çûn, Hatin, Xwarin', words: ['dixwim', 'dixwî', 'dixwe', 'dixwin', 'nan', 'mast', 'bazar', 'dibistan'] },
      { title: 'Pirsa û Olumsuz', words: ['ma', 'belê', 'na', 'naçim', 'nayê', 'naxwe', 'dizanim', 'nizanim'] },
      { title: 'Diyalogên Niha', words: ['her roj', 'niha', 'paşê', 'li gorî', 'hê jî', 'amade dike', 'ders', 'bersiv dide'] },
    ],
  },
  {
    id: 'unit13', levelId: 'level2', order: 13,
    title: 'Mala min', description: 'Ev ve oda tanımları', icon: '🏠',
    city: 'Nusaybin — Sınır çarşısı ve Nusaybin köprüsü',
    culturalHint: 'Baran Nusaybin\'de sınıra yakın bir evde konuk, oda oda Kürtçe öğreniyor.',
    lessons: [
      { title: 'Çûn', words: ['çûm', 'çûyî', 'çû', 'çûn', 'duh', 'îro', 'bazar', 'mal'] },
      { title: 'Hatin', words: ['hatim', 'hatî', 'hat', 'hatin', 'sibeh', 'êvar', 'dereng', 'niha'] },
      { title: 'Rabûn, Ketin, Man', words: ['rabûm', 'rabû', 'ketim', 'ket', 'mam', 'ma', 'zû', 'derve'] },
      { title: 'Dem û Rêza Bûyeran', words: ['berî', 'piştî', 'paşê', 'ji ber ku', 'duh êvar', 'heftê borî', 'nebûm', 'xweş bû'] },
      { title: 'Diyalogên Borî', words: ['kengê hatî?', 'tu çûyî ku?', 'çawa bû?', 'baş bû', 'nexweş bûm', 'derket', 'vegeriya', 'rastî'] },
    ],
  },
  {
    id: 'unit14', levelId: 'level2', order: 14,
    title: 'Hewaya dinyayê', description: 'Hava durumu ve mevsimler', icon: '🌤️',
    city: 'Midyat — Mor Gabriel Manastırı ve Tur Abdin platosu',
    culturalHint: 'Baran Tur Abdin\'in sıcağında şaşırıyor, manastır bahçesinde hava hakkında konuşuyorlar.',
    lessons: [
      { title: 'Min û Te', words: ['min', 'te', 'xwar', 'got', 'kir', 'nan', 'çay', 'duh'] },
      { title: 'Wî û Wê', words: ['wî', 'wê', 'dît', 'nivîsand', 'anî', 'name', 'pirtûk', 'heval'] },
      { title: 'Gotin, Dîtin, Xwendin', words: ['xwend', 'kirî', 'şand', 'bihîst', 'vexwar', 'peyam', 'kaxez', 'dikan'] },
      { title: 'Me, We, Wan', words: ['me', 'we', 'wan', 'stand', 'firot', 'amade kir', 'ders', 'parçe'] },
      { title: 'Diyalogên Demê Borî', words: ['çi kir?', 'nedît', 'negot', 'piştî wê', 'ji ber vê yekê', 'bersiv da', 'pirsa', 'rast'] },
    ],
  },
  {
    id: 'unit15', levelId: 'level2', order: 15,
    title: 'Rêwîtî', description: 'Seyahat ve ulaşım', icon: '🚌',
    city: 'Şırnak — İdil kasabası ve Dicle vadisi',
    culturalHint: 'Baran Amed\'den Şırnak\'a otobüsle gidiyor, yol boyunca Kürtçe konuşuyor.',
    lessons: [
      { title: 'Kengê, Çima, Çawa', words: ['kengê', 'çima', 'çawa', 'dereng', 'zû', 'ji ber ku', 'baş', 'nexweş'] },
      { title: 'Çend û Kî', words: ['çend', 'kî', 'kê', 'sal', 'lîre', 'bîst', 'bersiv', 'heval'] },
      { title: 'Ku û Ji Ku', words: ['li ku', 'ku', 'ji ku', 'li malê', 'li dibistanê', 'bazar', 'hatin', 'çûn'] },
      { title: 'Pirsên Têkel', words: ['bi kê re', 'ji bo çi', 'kîjan', 'çiqas', 'heta kengê', 'pê re', 'tenê', 'hilbijêre'] },
      { title: 'Diyalogên Pirsê', words: ['carinan', 'her tim', 'gelek caran', 'qet', 'niha', 'paşê', 'vegere', 'li benda te'] },
    ],
  },
  {
    id: 'unit16', levelId: 'level2', order: 16,
    title: 'Pêşe û kar', description: 'Meslekler ve iş hayatı', icon: '💼',
    city: 'Tunceli — Munzur Vadisi Milli Parkı',
    culturalHint: 'Baran Munzur\'da kamp yapıyor, farklı mesleklerden insanlarla tanışıyor.',
    lessons: [
      { title: 'Ez Nexweş Im', words: ['nexweş', 'tendurist', 'êş', 'şevat', 'giran', 'sivik', 'min ... heye', 'ez nexweş im'] },
      { title: 'Serê Min Diêşe', words: ['ser', 'zik', 'pişt', 'diran', 'çav', 'guh', 'diêşe', 'serê min diêşe'] },
      { title: 'Doktor û Derman', words: ['doktor', 'derman', 'reçete', 'muayene', 'derd', 'baş bibe', 'ba doktor', 'derman bide min'] },
      { title: 'Li Spîtarê', words: ['spîtar', 'nexweşxane', 'hemşîre', 'xwîn', 'ampûl', 'li benda te', 'nobet', 'ewle'] },
      { title: 'Tenduristî û Şîret', words: ['baş bûn', 'zû baş bibe', 'bihîne', 'av vexwe', 'derman bixwe', 'baştir', 'hest kirin', 'tenduristî'] },
    ],
  },
  {
    id: 'unit17', levelId: 'level2', order: 17,
    title: 'Xanî û cîwar', description: 'Komşuluk ve mahalle yaşamı', icon: '🏘️',
    city: 'Iğdır — Aras nehri kıyısı ve İran sınırı ovası',
    culturalHint: 'Baran Iğdır\'da bir Kürt ailesinin evinde konuk, sınır bölgesinin komşuluk kültürünü görüyor.',
    lessons: [
      { title: 'Pere û Baha', words: ['pere', 'baha', 'kirîn', 'firotin', 'dikan', 'bazar', 'hez dike', 'tune'] },
      { title: 'Ev Çend E?', words: ['çend', 'lîre', 'erzan', 'biha', 'kêm', 'zêde', 'nîv', 'kîlo'] },
      { title: 'Kirin û Pirsîn', words: ['ez dixwazim bikrim', 'heye?', 'belê', 'na', 'bide min', 'ji bo', 'yek', 'du'] },
      { title: 'Erzan û Biha', words: ['erzan', 'biha', 'erzantir', 'bihatir', 'baştir', 'kêmtir', 'zêdetir', 'li gorî'] },
      { title: 'Diyalogên Bazarê', words: ['çi dixwazî?', 'çiqas?', 'yek kîlo', 'nîv kîlo', 'qediya', 'paşê were', 'spas', 'xêr be'] },
    ],
  },
  {
    id: 'unit18', levelId: 'level2', order: 18,
    title: 'Xwarin çêkirin', description: 'Yemek yapma ve tarifler', icon: '🍳',
    city: 'Ağrı — Tendürek volkanı eteği ve Ağrı ovası',
    culturalHint: 'Baran çoban ailesinin çadırında kalıyor, dapîr Berfin köy ekmeği ve tandır yemekleri öğretiyor.',
    lessons: [
      { title: 'Hewa Çawa Ye?', words: ['hewa', 'çawa', 'germ', 'sar', 'xweş', 'xerab', 'geş', 'ewrî'] },
      { title: 'Baran û Berf', words: ['baran', 'berf', 'ba', 'tav', 'dibare', 'dide', 'xurt', 'hêdî'] },
      { title: 'Demsalên Salê', words: ['bihar', 'havîn', 'payîz', 'zivistan', 'demsal', 'di ... de', 'gul', 'pel'] },
      { title: 'Xweza û Cografya', words: ['xweza', 'çiya', 'çem', 'behr', 'daristan', 'zevî', 'gund', 'bilind'] },
      { title: 'Diyalogên Hewayê', words: ['ezmân', 'ewr', 'teyar', 'birûsk', 'hewa guherî', 'baran tê', 'şemsiye', 'derkevin derve'] },
    ],
  },
  {
    id: 'unit19', levelId: 'level2', order: 19,
    title: 'Diyalog û pirsên nû', description: 'Günlük diyaloglar ve sorular', icon: '💬',
    city: 'Kars — Ani harabeleri ve Kars çarşısı',
    culturalHint: 'Baran Ani harabelerinde Kürt turistlerle tanışıyor, artık günlük konuşma kurabiliyor.',
    lessons: [
      { title: 'Mal û Beşên Wê', words: ['mal', 'li malê', 'salon', 'mitbax', 'serşok', 'odeya xewê', 'derî', 'pencere'] },
      { title: 'Jûr û Avahî', words: ['jûr', 'avahî', 'hewş', 'baxçe', 'merdiwen', 'banî', 'li jorê', 'li jêrê'] },
      { title: 'Mobîlya û Cih', words: ['mobîlya', 'kursî', 'mase', 'nivîn', 'kanap', 'qefldan', 'li ser', 'li ber'] },
      { title: 'Karên Di Malê de', words: ['rûniştin', 'pijandin', 'paqij kirin', 'vekirin', 'girtin', 'temaşe kirin', 'amade kirin', 'bêhna xwe dan'] },
      { title: 'Mêvan û Diyalogên Malê', words: ['mêvan', 'xweş hatî', 'xweş hatin', 'bixûr', 'rûne', 'rûnin', 'çay bînim', 'mal û malî xweş be'] },
    ],
  },
  {
    id: 'unit20', levelId: 'level2', order: 20,
    title: 'Nêzîkbûn û hevaltî', description: 'Arkadaşlık kurma ve sosyal ilişkiler', icon: '🤝',
    city: 'Elazığ — Harput kalesi ve Keban barajı',
    culturalHint: 'Baran Harput\'ta Kürtçesiyle yeni dostlar ediniyor, Berfin de İstanbul\'dan izliyor.',
    lessons: [
      { title: 'Silav û Rewşpirsîn', words: ['silav', 'tu çawa yî?', 'hûn çawa ne?', 'ez baş im', 'kêfa min baş e', 'spas', 'navê te çi ye?', 'navê min ... e'] },
      { title: 'Ji Ku Yî?', words: ['ji ku', 'tu ji ku yî?', 'ez ji ... me', 'li ku dijî?', 'dijîm', 'bajêr', 'welat', 'stenbol'] },
      { title: 'Kar û Nasname', words: ['tu çi dikî?', 'mamoste', 'bijîşk', 'xwendekar', 'karmend', 'bazirgan', 'kar kirin', 'li dibistanê'] },
      { title: 'Rê û Cih', words: ['rê', 'li ku ye?', 'rast', 'çep', 'rasterast', 'nêzî', 'dûr', 'kolane'] },
      { title: 'Diyalogên Temam', words: ['bibore', 'ji kerema xwe', 'xêr be', 'dizanim', 'hindek', 'kurmancî', 'oxir be', 'heta paşê'] },
    ],
  },

  // ─── SEVİYE 3 — B1 ───
  {
    id: 'unit21', levelId: 'level3', order: 21,
    title: 'Çîrok û dîrok', description: 'Hikayeler ve geçmiş zaman', icon: '📖',
    city: 'Hewlêr (Erbil) — Erbil kalesi ve büyük bazaar',
    culturalHint: 'Kurdo Hewlêr kalesinin gölgesinde Baran\'a Kurdistan\'ın tarihi hikayelerini anlatıyor.',
    lessons: [
      { title: 'Seet Çend e?', words: ['seet', 'çend', 'nîv', 'çarêk', 'deqîqe', 'kêm', 'û', 'di saetê de'] },
      { title: 'Demên Rojê', words: ['sibê', 'sibehê', 'nîvro', 'piştî nîvro', 'êvar', 'êvarê', 'şev', 'nîvşev'] },
      { title: 'Rojên Hefteyê', words: ['yekşem', 'duşem', 'sêşem', 'çarşem', 'pêncşem', 'în', 'şemî', 'hefte'] },
      { title: 'Meh û Demsal', words: ['meh', 'çile', 'sibat', 'adar', 'nîsan', 'gulan', 'hezîran', 'demsal'] },
      { title: 'Plan û Randevu', words: ['kengê', 'randevu', 'dicivin', 'bimîne', 'dereng', 'zû', 'amade', 'civîn'] },
    ],
  },
  {
    id: 'unit22', levelId: 'level3', order: 22,
    title: 'Xweza û jîngeh', description: 'Doğa ve çevre', icon: '🌿',
    city: 'Silêmanî (Süleymaniye) — Azmar gölü ve dağ manzarası',
    culturalHint: 'Kurdo û Berfin Silêmanî\'nin dağlarında Kürtçe şiir ve doğa kelimeleri öğreniyor.',
    lessons: [
      { title: 'Niha Çi Dikî?', words: ['niha', 'dikim', 'dikî', 'dixwînim', 'dinivîsim', 'dixwim', 'guhdarî dikim', 'temaşe dikim'] },
      { title: 'Li Ku Yî?', words: ['li ku', 'li malê', 'li dibistanê', 'li kafeyê', 'li ofîsê', 'li derve', 'rûniştim', 'rawestim'] },
      { title: 'Ew Çi Dike?', words: ['ew', 'diaxive', 'dixebite', 'dilîze', 'radizê', 'digerin', 'dixebitin', 'diaxivin'] },
      { title: 'Rewşa Laş û Hest', words: ['birçî me', 'tî me', 'westiyayî me', 'amade me', 'mijûl im', 'vala me', 'kêfxweş im', 'hinekî'] },
      { title: 'Diyalogên Niha', words: ['tu li ku yî?', 'tu niha çi dikî?', 'ez tênê me', 'dem baş e?', 'paşê diaxivîn', 'hinekî dereng im', 'ez digihîjim', 'li benda te me'] },
    ],
  },
  {
    id: 'unit23', levelId: 'level3', order: 23,
    title: 'Huner û çand', description: 'Sanat ve kültür', icon: '🎨',
    city: 'Duhok — Zakho köprüsü ve Duhok platosu',
    culturalHint: 'Festîvala dengbêjan li Duhokê — Kurdo stranbêjan dinê, Baran û Berfin govend dikin.',
    lessons: [
      { title: 'Dê + Çûn', words: ['dê', 'sibê', 'paşê', 'hefteya bê', 'biçim', 'biçî', 'biçe', 'biçin'] },
      { title: 'Planên Nêzîk', words: ['bêm', 'bê', 'bên', 'bikim', 'bike', 'bixwim', 'vexwim', 'bixwîne'] },
      { title: 'Pêşeroja Neyînî', words: ['neçim', 'neçe', 'neyêm', 'neyê', 'nexwim', 'nevexwim', 'nebikim', 'nexwîne'] },
      { title: 'Pirsên Pêşerojê', words: ['ma', 'kengê', 'li ku', 'bi kê re', 'çima', 'çi', 'erê', 'na'] },
      { title: 'Karma Pêşeroj', words: ['sala bê', 'sibe sibehê', 'êvarê', 'nîvro', 'şevê', 'plan', 'biguhere', 'derkeve'] },
    ],
  },
  {
    id: 'unit24', levelId: 'level3', order: 24,
    title: 'Teknolojî', description: 'Teknoloji ve internet', icon: '💻',
    city: 'Amadiye — Antik Amadiye şehri (dağ tepesindeki şehir)',
    culturalHint: 'Baran wifi\'nin kesildiği Amadiye\'de telefon Kürtçesine ayarlıyor, Berfin ona uygulamaları anlatıyor.',
    lessons: [
      { title: 'Ji ... -tir', words: ['ji', '-tir', 'mezintir', 'piçûktir', 'dirêjtir', 'kurttir', 'dûrtir', 'nêzîktir'] },
      { title: 'Rengdêrên Berhevkirinê', words: ['baştir', 'xirabtir', 'germtir', 'sartir', 'bihatir', 'erzantir', 'grantir', 'siviktir'] },
      { title: 'Herî (En Üstünlük)', words: ['herî', 'herî mezin', 'herî piçûk', 'herî baş', 'herî xweş', 'herî bilind', 'herî nizm', 'herî nêzîk'] },
      { title: 'Eşitlik ve Olumsuz Karşılaştırma', words: ['mîna', 'wekî', 'ewqas', 'ne ewqas', 'heman', 'nîne', 'wekhev', 'cudahî'] },
      { title: 'Karma Berhevdan', words: ['berhevdan', 'cudahî', 'hemûyan', 'ji ya din', 'bajar', 'gund', 'rê', 'hilbijartin'] },
    ],
  },
  {
    id: 'unit25', levelId: 'level3', order: 25,
    title: 'Dibistan û xwendin', description: 'Okul ve eğitim', icon: '📚',
    city: 'Zaho — Habur sınır kapısı ve Khabur nehri',
    culturalHint: 'Baran Zaho\'da Kürtçe eğitim veren bir okulu ziyaret ediyor.',
    lessons: [
      { title: 'Çawa? Hal Zarfları', words: ['zû', 'hêdî', 'baş', 'xweş', 'rast', 'çewt', 'bi baldarî', 'bi dilê xwe'] },
      { title: 'Çiqas? Derece Zarfları', words: ['gelek', 'pir', 'kêm', 'zêde', 'hinekî', 'bi temamî', 'hema hema', 'tenê'] },
      { title: 'Kengê? Zaman Zarfları', words: ['niha', 'êdî', 'hîn', 'berê', 'paşê', 'carinan', 'her dem', 'her roj'] },
      { title: 'Li ku? Yer Zarfları', words: ['li vir', 'li wir', 'li pêş', 'li pişt', 'li jêr', 'li jor', 'li nêzîk', 'li dûr'] },
      { title: 'Karma Zaravan', words: ['bi hêsanî', 'bi zorî', 'bi carekê', 'bi ser û ber', 'her roj', 'carinan', 'li derve', 'li hundur'] },
    ],
  },
  {
    id: 'unit26', levelId: 'level3', order: 26,
    title: 'Werzîş û lîstin', description: 'Spor ve oyun', icon: '⚽',
    city: 'Kerkük — Kerkük kalesi ve Kürdistan sınırı',
    culturalHint: 'Kurdo û Baran Kerkük stadyumunda mahalle futbol maçını izliyor.',
    lessons: [
      { title: 'Eger ... dê ...', words: ['eger', 'dê', 'baran', 'bê', 'xebat kirin', 'biserketin', 'xweş bûn', 'neçin'] },
      { title: 'Heke û Wê demê', words: ['heke', 'wê demê', 'wê çaxê', 'zû rabûn', 'dereng man', 'destpêkirin', 'baş be', 'derve'] },
      { title: 'Olumsuz Koşul', words: ['neyê', 'neçî', 'nexwîne', 'nexwe', 'nexweş ketin', 'tengav bûn', 'alîkarî', 'derbas bûn'] },
      { title: 'Koşul Soruları', words: ['çi bikî', 'çi bikin', 'ma eger', 'li ku', 'kengê', 'bibêjî', 'biryar', 'guhertin'] },
      { title: 'Karma Şert û Merc', words: ['hewa', 'xirab be', 'pêwîst e', 'bimîne', 'bixwazî', 'bikaribî', 'ji min re', 'dem be dem'] },
    ],
  },
  {
    id: 'unit27', levelId: 'level3', order: 27,
    title: 'Civak û siyaset', description: 'Toplum ve sosyal konular', icon: '🏛️',
    city: 'Halabja — Şehitler anıtı ve Halabja müzesi',
    culturalHint: 'Baran Halabja anıtında derin sessizlikte duruyor, Kurdo tarih ve toplum hakkında anlatıyor.',
    lessons: [
      { title: 'Dibistan û Zanîngeh', words: ['dibistan', 'zanîngeh', 'lîse', 'xwendekar', 'mamoste', 'sinif', 'pirtûkxane', 'xwendin'] },
      { title: 'Ders û Sînav', words: ['ders', 'sînav', 'not', 'êdev', 'derbas bûn', 'amade kirin', 'zehmet', 'hêsan'] },
      { title: 'Mamoste û Xwendekar', words: ['hîn kirin', 'hîn bûn', 'pirsîn', 'bersiv dan', 'fam kirin', 'ji bîr kirin', 'dubare kirin', 'bibore'] },
      { title: 'Zanistên Dibistanê', words: ['matematîk', 'zanist', 'dîrok', 'jeografya', 'wênesazî', 'mûzîk', 'bedenî', 'bijarte'] },
      { title: 'Karma Xwendin', words: ['mezûn bûn', 'qeyd kirin', 'burs', 'dîploma', 'roja yekem', 'beş', 'xwendina bilind', 'hevalên baş'] },
    ],
  },
  {
    id: 'unit28', levelId: 'level3', order: 28,
    title: 'Dema bê', description: 'Gelecek zaman ve planlar', icon: '🔮',
    city: 'Rawanduz — Şah vadisi kanyonu ve dağ geçidi',
    culturalHint: 'Baran û Berfin Rawanduz\'un nefes kesen manzarasında pêşerojê ji bo hev xeyalên xwe parvî dikin.',
    lessons: [
      { title: 'Balafir û Rêwîtî', words: ['geşt', 'rêwîtî', 'balafir', 'balafirge', 'bîlet', 'çante', 'rêwî', 'firin'] },
      { title: 'Welat û Bajêr', words: ['welat', 'bajêr', 'gund', 'nexşe', 'derve', 'navend', 'nêzîk', 'dûr'] },
      { title: 'Otêl û Rûniştin', words: ['otêl', 'ode', 'rezervasyon', 'mêvan', 'mêvanxane', 'şev', 'bihayê', 'vala'] },
      { title: 'Sînor û Pasaport', words: ['pasaport', 'vîze', 'sînor', 'gumrik', 'destûr', 'nasname', 'derbaz bûn', 'winda kirin'] },
      { title: 'Karma Geştiyarî', words: ['tûrîst', 'wêne kişandin', 'bîranîn', 'şûn', 'şûnên dîrokî', 'vegerin', 'rêzik', 'geşta baş'] },
    ],
  },
  {
    id: 'unit29', levelId: 'level3', order: 29,
    title: 'Bêjeyên tevlihev', description: 'Fiil çekimi ve karmaşık yapılar', icon: '🔤',
    city: 'Ranya — Dukan barajı gölü kıyısı',
    culturalHint: 'Kurdo Dukan gölü kenarında Baran û Berfin\'e rêzimana kurdî dişiband.',
    lessons: [
      { title: 'Xwarin û Vexwarin', words: ['xwarin', 'vexwarin', 'nan', 'av', 'goşt', 'şîr', 'hêk', 'mast'] },
      { title: 'Xwaringeh û Siparîş', words: ['xwaringeh', 'menu', 'siparîş', 'hesab', 'garson', 'mase', 'birçî', 'têr'] },
      { title: 'Xwarin Amade Kirin', words: ['amade kirin', 'pijandin', 'pijîn', 'şûştin', 'birîn', 'tava', 'çêj', 'xwê'] },
      { title: 'Tam û Bêhn', words: ['şêrîn', 'tirş', 'tûj', 'xweş', 'xirab', 'germ', 'sar', 'bêhn'] },
      { title: 'Karma Xwarin', words: ['mêwe', 'sebze', 'çay', 'qehwe', 'xwarinxane', 'şekir', 'rûn', 'bazar'] },
    ],
  },
  {
    id: 'unit30', levelId: 'level3', order: 30,
    title: 'Gotinên hevpar', description: 'Deyimler ve atasözleri', icon: '💬',
    city: 'Pêncwîn — Hewraman dağları ve İran sınırı',
    culturalHint: 'Dapîra Berfin Hewraman\'ın zirvesinde Baran\'a Kürtçe atasözlerini öğretiyor.',
    lessons: [
      { title: 'Cejn û Pîrozbahî', words: ['cejn', 'pîrozbahî', 'pîroz be', 'şahî', 'dawet', 'kêf', 'diyarî', 'bextewar'] },
      { title: 'Newroz', words: ['newroz', 'bihar', 'agir', 'kulîlk', 'xwezayî', 'azadî', 'jiyan', 'sersal'] },
      { title: 'Kevneşopî û Adet', words: ['kevneşopî', 'adet', 'çand', 'mîras', 'dengbêj', 'kilam', 'govend', 'cil û berg'] },
      { title: 'Civat û Gel', words: ['civat', 'gel', 'komel', 'hevkarî', 'biratî', 'aştî', 'maf', 'yekîtî'] },
      { title: 'Karma Çand', words: ['ziman', 'kurdî', 'nasname', 'serbilindî', 'xwedîkirin', 'parastin', 'bîranîn', 'pêşeroj'] },
    ],
  },

  // ─── SEVİYE 4 — B2 ───
  {
    id: 'unit31', levelId: 'level4', order: 31,
    title: 'Pîşe û Kar', description: 'B2 seviye içerik', icon: '💼',
    city: 'Qamişlo (Kuzey Suriye) — sınır çarşısı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Pîşe û Karên Bingehîn', words: ['pîşe', 'doktor', 'mamosta', 'endezyar', 'parêzer', 'çandinîkar', 'xebatkar', 'bazirgan'] },
      { title: 'Cihê Karê', words: ['kar', 'karxane', 'nexweşxane', 'dibistan', 'zanîngeh', 'ofîs', 'dikan', 'xwaringeh'] },
      { title: 'Di Karê De', words: ['kar kirin', 'civîn', 'rapor', 'berpirsiyar', 'serkar', 'hevalê karê', 'mesref', 'betlane'] },
      { title: 'Hevdîtin û Karê Nû', words: ['hevdîtin', 'serîldan', 'jêhatî', 'ezmûn', 'serkeftin', 'pêşniyar', 'destpêkirin', 'qedandin'] },
      { title: 'Karma Pîşe û Kar', words: ['xebat', 'armanc', 'pêşkeftin', 'serkeftî', 'texsîr', 'navdar', 'karnas', 'plan'] },
    ],
  },
  {
    id: 'unit32', levelId: 'level4', order: 32,
    title: 'Teknolojî', description: 'B2 seviye içerik', icon: '🖥️',
    city: 'Dirbêsiyê — Cizîra Botanê ovası',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Amûrên Teknolojiyê', words: ['teknolojî', 'amûr', 'têlefon', 'komputer', 'tablêt', 'kamera', 'televîzyon', 'batarya'] },
      { title: 'Înternet û Pêwendî', words: ['înternet', 'pêwendî', 'malper', 'e-name', 'şîfre', 'daxistin', 'barkirin', 'tor'] },
      { title: 'Medyaya Civakî', words: ['medyaya civakî', 'peyam', 'wêne', 'parve kirin', 'hez kirin', 'şopandin', 'lêgerîn', 'şîrove'] },
      { title: 'Komputer û Bername', words: ['dosya', 'bername', 'kilavye', 'ekran', 'tomarkirin', 'çapkirin', 'vekirî', 'girtî'] },
      { title: 'Karma Teknolojî', words: ['xelet', 'pirsgirêk', 'çareserkirin', 'nûkirin', 'sererastekirin', 'bilez', 'hêdî', 'alîkarî'] },
    ],
  },
  {
    id: 'unit33', levelId: 'level4', order: 33,
    title: 'Spor û Werzîş', description: 'B2 seviye içerik', icon: '⚽',
    city: 'Kobanê — yeniden inşa edilen şehir',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Werzîş û Tevger', words: ['werzîş', 'werzîş kirin', 'bezîn', 'avjenî', 'bisîklet', 'siwar bûn', 'çiyakirin', 'tevger'] },
      { title: 'Lîstikên Topê', words: ['top', 'futbol', 'voleybol', 'tîm', 'lîstikvan', 'qada', 'gol xistin', 'temaşe kirin'] },
      { title: 'Beden û Tenduristî', words: ['beden', 'tenduristî', 'dest', 'pê', 'serî', 'zik', 'xurt', 'saxlem'] },
      { title: 'Pêşbirk û Serfirazî', words: ['pêşbirk', 'serfiraz', 'qezandin', 'winda kirin', 'madalya', 'xelat', 'antrenman', 'koç'] },
      { title: 'Karma Werzîşê', words: ['stadyom', 'temaşevan', 'rêzik', 'heyecan', 'bijare', 'şampiyonî', 'ezmûndar', 'westiyan'] },
    ],
  },
  {
    id: 'unit34', levelId: 'level4', order: 34,
    title: 'Hest û Hizir', description: 'B2 seviye içerik', icon: '❤️',
    city: 'Efrîn — zeytin bahçeleri ve dağlar',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Hestên Erênî', words: ['şayî', 'şa bûn', 'hez kirin', 'evîn', 'hêvî', 'aramî', 'kêf', 'serbilind'] },
      { title: 'Hestên Neyênî', words: ['xemgîn', 'xem', 'tirs', 'tirsîn', 'hêrs', 'hêrs bûn', 'westî', 'dilşikestî'] },
      { title: 'Îfadekirina Hestan', words: ['hest', 'hest kirin', 'nîşan dan', 'diyar kirin', 'gotin', 'kenîn', 'girîn', 'veşartin'] },
      { title: 'Hizir û Ramandin', words: ['fikirîn', 'fikir', 'biryar', 'biryar dan', 'xewn', 'xewn dîtin', 'zanîn', 'bawer kirin'] },
      { title: 'Karma Hest û Hizir', words: ['dil', 'dilxweşî', 'razî bûn', 'pê xweş bûn', 'ecêb man', 'aciz bûn', 'bi dilê xwe', 'ji xwe razî'] },
    ],
  },
  {
    id: 'unit35', levelId: 'level4', order: 35,
    title: 'Dirav û Darayî', description: 'B2 seviye içerik', icon: '💰',
    city: 'Hesekê — Kuzey Suriye çarşısı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Dirav û Bihayê', words: ['dirav', 'biha', 'erzan', 'bihayê', 'nirx', 'lîre', 'dolar', 'euro'] },
      { title: 'Bank û Hesab', words: ['bank', 'hesab', 'hesab vekirin', 'dirav danîn', 'dirav hildan', 'veguheztin', 'karta bankê', 'deyn'] },
      { title: 'Kirrîn û Firotin', words: ['kirrîn', 'firotin', 'bazar', 'firoşgeh', 'firoşkar', 'mişterî', 'daxistin', 'peyda kirin'] },
      { title: 'Xercê Malê', words: ['xerc', 'xercê malê', 'kirê', 'fatura', 'mehane', 'berçav', 'serf kirin', 'teseruf kirin'] },
      { title: 'Karma Dirav û Darayî', words: ['darayî', 'mûçe', 'bac', 'dewlemend', 'feqîr', 'kêm', 'têrî kirin', 'birêve birin'] },
    ],
  },
  {
    id: 'unit36', levelId: 'level4', order: 36,
    title: 'Cil û Berg', description: 'B2 seviye içerik', icon: '👗',
    city: 'Serêkaniyê — Tell Abyad yolu',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Cilên Bingehîn', words: ['cil', 'kiras', 'şalwar', 'pêlav', 'corap', 'kulav', 'celatek', 'paqij'] },
      { title: 'Cilên Demsalê', words: ['zivistan', 'havîn', 'palto', 'destmal', 'destên', 'şortik', 'sandal', 'germ'] },
      { title: 'Reng û Şêweya Cil', words: ['reng', 'şêwe', 'mezin', 'biçûk', 'dirêj', 'kurt', 'nû', 'kevin'] },
      { title: 'Kirrîna Cilên', words: ['kirîn', 'dikan', 'hejmar', 'firoke', 'pêşan dayîn', 'guherîn', 'biha', 'erzan'] },
      { title: 'Karma Cil û Berg', words: ['moda', 'stîl', 'xweşik', 'civandî', 'rengîn', 'cilê neteweyî', 'berg', 'li min dike'] },
    ],
  },
  {
    id: 'unit37', levelId: 'level4', order: 37,
    title: 'Muzîk û Huner', description: 'B2 seviye içerik', icon: '🎵',
    city: 'Tirbespiyê — kırsal Kürt köyü',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Muzîk û Stranbêjî', words: ['muzîk', 'stran', 'stranbêj', 'goranî', 'dengbêj', 'deng', 'guhdarî kirin', 'stran gotin'] },
      { title: 'Amûrên Muzîkê', words: ['amûrên muzîkê', 'bilûr', 'dîlan', 'saz', 'keman', 'piyano', 'lêxistin', 'cûrbecûr'] },
      { title: 'Hunera Xêzkirin', words: ['huner', 'xêzkirin', 'wêne', 'wênesaz', 'wênesazî', 'boyax', 'reng', 'hunermend'] },
      { title: 'Sînema û Şano', words: ['sînema', 'fîlm', 'şano', 'lîstik', 'lîstikvan', 'derhêner', 'temaşe kirin', 'dîmen'] },
      { title: 'Karma Huner', words: ['huner', 'çand', 'mîras', 'hunera kurdî', 'biafirîn', 'afirîner', 'hunergeh', 'dewlemend'] },
    ],
  },
  {
    id: 'unit38', levelId: 'level4', order: 38,
    title: 'Veguheztin', description: 'B2 seviye içerik', icon: '🚌',
    city: 'Derik (Mêşkê) — Kuzey Suriye',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Wesayîtên Bejahî', words: ['wesayît', 'otobûs', 'trên', 'erebe', 'bisîklet', 'motorsîklet', 'camyon', 'ajokar'] },
      { title: 'Rêwîtiya Hewayî', words: ['firroke', 'balafir', 'balafirge', 'bilêt', 'çantel', 'pasaport', 'rêwîtî', 'dereng'] },
      { title: 'Wesayîtên Avê', words: ['keştî', 'kayik', 'bender', 'kaptan', 'çem', 'derya', 'gol', 'rêya avê'] },
      { title: 'Stasyon û Seferan', words: ['stasyon', 'rawestgeh', 'qereqol', 'rêwî', 'sefer', 'saet', 'kontrol', 'rê'] },
      { title: 'Karma Veguheztin', words: ['veguheztin', 'rêwîtî', 'çûn', 'hatin', 'gihîştin', 'derbas bûn', 'rêwî', 'bi xêr hatin'] },
    ],
  },
  {
    id: 'unit39', levelId: 'level4', order: 39,
    title: 'Hawirdor û Xweza', description: 'B2 seviye içerik', icon: '🌿',
    city: 'Girkê Legê — Khabur vadisi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Xweza û Zevî', words: ['xweza', 'çiya', 'zevî', 'dar', 'daristân', 'çem', 'gol', 'gelî'] },
      { title: 'Heywan û Nebat', words: ['heywan', 'heywanên kovî', 'gurg', 'hirç', 'rovî', 'çûk', 'masî', 'kulîlk'] },
      { title: 'Hawirdora Bajêr', words: ['bajar', 'park', 'kolan', 'avahî', 'tax', 'derdor', 'hawirdor', 'paqij'] },
      { title: 'Pirsgirêkên Hawirdorê', words: ['pirsgirêk', 'qirêjî', 'av qirêj', 'qirêjiya hewayê', 'germbûna hewayê', 'dara birîn', 'zivirandin', 'parastina xwezayê'] },
      { title: 'Karma Hawirdor', words: ['xweza', 'asman', 'baran', 'berf', 'tav', 'ba', 'ax', 'kesk'] },
    ],
  },
  {
    id: 'unit40', levelId: 'level4', order: 40,
    title: 'Rewşên Acîl', description: 'B2 seviye içerik', icon: '🚨',
    city: 'Rimelan — petrol bölgesi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Alîkarî û Nexweşî', words: ['alîkarî', 'alîkarî bike', 'acîl', 'nexweş', 'birîn', 'ambalans', 'êş', 'alîkariya yekem'] },
      { title: 'Polîs û Ewlekarî', words: ['polîs', 'ewlekarî', 'dizî', 'xeter', 'xeterî', 'rizgarkirin', 'destgirtin', 'jandarm'] },
      { title: 'Agir û Xetereyê', words: ['agir', 'yangîn', 'agirkuj', 'dûman', 'xeter', 'herikîn', 'erdhej', 'dûr bimîne'] },
      { title: 'Nexweşxane û Derman', words: ['nexweşxane', 'doktor', 'derman', 'dermansaz', 'dermanxane', 'êş', 'hemşîre', 'koma xwînê'] },
      { title: 'Karma Rewşên Acîl', words: ['rewşa acîl', 'telefon bike', 'bixwîne', 'birevin', 'rawestin', 'qeza', 'ji kerema xwe', 'ne bitirse'] },
    ],
  },

  // ─── SEVİYE 5 — C1 ───
  {
    id: 'unit41', levelId: 'level5', order: 41,
    title: 'Siyaset û Civat', description: 'C1 seviye içerik', icon: '🏛️',
    city: 'Urmiye (İran) — Urmiye gölü kıyısı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Dewlet û Hukûmet', words: ['dewlet', 'hukûmet', 'serok', 'serokwezîr', 'wezaret', 'zagon', 'parlamento', 'destûra bingehîn'] },
      { title: 'Hilbijartin û Deng', words: ['hilbijartin', 'deng', 'deng dan', 'namzed', 'partî', 'sindoqa dengan', 'komar', 'demokrasî'] },
      { title: 'Maf û Azadî', words: ['maf', 'azadî', 'wekhevî', 'dad', 'dadgeh', 'mafên mirovan', 'aştî', 'parastin'] },
      { title: 'Civat û Gel', words: ['civat', 'gel', 'netew', 'welatî', 'çand', 'ziman', 'nasname', 'hevgirtî'] },
      { title: 'Karma Siyasî', words: ['siyaset', 'rêxistin', 'navend', 'piştgirî', 'xebat', 'têkoşîn', 'berxwedan', 'beşdarî'] },
    ],
  },
  {
    id: 'unit42', levelId: 'level5', order: 42,
    title: 'Medya û Ragihandin', description: 'C1 seviye içerik', icon: '📺',
    city: 'Mahabad (İran) — Kürdistan Cumhuriyeti başkenti',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Rojname û Kovar', words: ['rojname', 'kovar', 'gotar', 'nivîskar', 'xwendevan', 'weşandin', 'sernav', 'çapemenî'] },
      { title: 'Televizyon û Radyo', words: ['televizyon', 'radyo', 'kanal', 'bername', 'weşan', 'pêşkêşkar', 'guhdar', 'temaşevan'] },
      { title: 'Înternet û Medya Civakî', words: ['înternet', 'medya civakî', 'malper', 'peyam', 'şandin', 'girêdan', 'sepan', 'parvekirin'] },
      { title: 'Nûçe û Rastî', words: ['nûçe', 'xeber', 'nûçevan', 'wênegir', 'sererastkar', 'çavkanî', 'rastî', 'nûçeya derewîn'] },
      { title: 'Karma Ragihandin', words: ['ragihandin', 'agahî', 'deng', 'wêne', 'vîdyo', 'navgîn', 'azadiya çapemeniyê', 'agahî dan'] },
    ],
  },
  {
    id: 'unit43', levelId: 'level5', order: 43,
    title: 'Çand û Wêje', description: 'C1 seviye içerik', icon: '🎭',
    city: 'Kirmanşah — Bistun yazıtları',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Helbest û Stran', words: ['helbest', 'helbestvan', 'stran', 'dengbêj', 'biwêj', 'awaz', 'rîtm', 'wate'] },
      { title: 'Çîrok û Roman', words: ['çîrok', 'roman', 'nivîskar', 'xwendevan', 'leheng', 'berhem', 'beş', 'vegotin'] },
      { title: 'Kevneşopî û Cejn', words: ['kevneşopî', 'cejn', 'newroz', 'govend', 'cilê kurdî', 'ziyaret', 'merasîm', 'agir'] },
      { title: 'Dengbêjî û Mûzîk', words: ['dengbêjî', 'kilam', 'mûzîk', 'bilûr', 'def', 'tembûr', 'deng', 'guhdar'] },
      { title: 'Karma Çand û Wêje', words: ['çand', 'wêje', 'mîras', 'nasname', 'zimanê dayikê', 'zindî', 'parastin', 'veguheztin'] },
    ],
  },
  {
    id: 'unit44', levelId: 'level5', order: 44,
    title: 'Dîrok û Kevnarî', description: 'C1 seviye içerik', icon: '🏺',
    city: 'Sine/Sanandaj — İran Kürdistanı başkenti',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Dîroka Kevnar', words: ['dîrok', 'kevnar', 'serdema berê', 'bûyer', 'dîroknas', 'belgename', 'muzexane', 'şahidî'] },
      { title: 'Bajar û Şaristanî', words: ['bajar', 'şaristanî', 'keleh', 'avahî', 'navend', 'gund', 'kevnare', 'arkeolojî'] },
      { title: 'Şervan û Qehremanî', words: ['şervan', 'şer', 'leheng', 'qehremanî', 'serkeftin', 'berxwedan', 'azadî', 'aştî'] },
      { title: 'Mîr û Desthilat', words: ['mîr', 'padîşah', 'desthilat', 'dewlet', 'serwerî', 'eşîr', 'birêvebirin', 'peyman'] },
      { title: 'Karma Dîrok û Mîras', words: ['mîras', 'bîranîn', 'nifş', 'dema kevnar', 'şopandin', 'parastin', 'veguheztin', 'çandî'] },
    ],
  },
  {
    id: 'unit45', levelId: 'level5', order: 45,
    title: 'Din û Bawerî', description: 'C1 seviye içerik', icon: '🕌',
    city: 'Şino/Ushnuyeh — Urmiye gölü batısı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Bawerî û Ol', words: ['ol', 'bawerî', 'xwedê', 'pêxember', 'pîroz', 'nimêj', 'dua', 'misilman'] },
      { title: 'Cihên Pîroz', words: ['cihê pîroz', 'mizgeft', 'goristên', 'ziyaret', 'xanqah', 'mihrab', 'minare', 'ezan'] },
      { title: 'Pratîkên Dînî', words: ['rojî', 'remezan', 'dua', 'îbadet', 'heç', 'zekat', 'qurban', 'feqîr'] },
      { title: 'Çand û Adet', words: ['adet', 'nîşane', 'sersal', 'newroz', 'cejn', 'merasîm', 'kevneşopî', 'dawet'] },
      { title: 'Karma Din û Bawerî', words: ['ruh', 'cennet', 'dujeh', 'guneh', 'qeder', 'rehm', 'şukur', 'bexşîn'] },
    ],
  },
  {
    id: 'unit46', levelId: 'level5', order: 46,
    title: 'Felsefe û Hiş', description: 'C1 seviye içerik', icon: '🧠',
    city: 'Serdêşt/Sardasht — dağ vadisi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Felsefî Têgeh', words: ['felsefe', 'fikir', 'pirs', 'zanist', 'zanyarî', 'aqil', 'têgeh', 'feylesof'] },
      { title: 'Hiş û Aqil', words: ['hişmendî', 'têgihiştin', 'fikirîn', 'bîr', 'xeyal', 'hest', 'aqil', 'baldarî'] },
      { title: 'Rastî û Derewê', words: ['rastî', 'derew', 'şik', 'îspat', 'bawerî', 'xeletî', 'delîl', 'durust'] },
      { title: 'Jiyan û Mirin', words: ['jiyan', 'mirin', 'hebûn', 'tunebûn', 'wate', 'mebest', 'dem', 'bextiyarî'] },
      { title: 'Karma Felsefe û Hiş', words: ['wekhevî', 'azadî', 'maf', 'wijdan', 'rêz', 'berpirsiyarî', 'dad', 'aştî'] },
    ],
  },
  {
    id: 'unit47', levelId: 'level5', order: 47,
    title: 'Aborî û Bazirganî', description: 'C1 seviye içerik', icon: '💹',
    city: 'Bukan — Saruq ovası',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Aborî', words: ['aborî', 'bazar', 'mal û milk', 'hilberîn', 'xercîkirin', 'berhevkirin', 'buhayê bazarê', 'pêdivî'] },
      { title: 'Bazirganî', words: ['bazirganî', 'bazirgan', 'kirîn', 'firotin', 'hinardekirin', 'têkêşkirin', 'sozname', 'fatûra'] },
      { title: 'Banke û Darayî', words: ['bank', 'darayî', 'hesab', 'deyn', 'faîz', 'veguheztin', 'sigorte', 'pere'] },
      { title: 'Karê Serbixwe', words: ['karê serbixwe', 'pargîdan', 'veberhênan', 'qezenc', 'windakirin', 'hevkar', 'pêşniyar', 'budce'] },
      { title: 'Karma Aborî', words: ['xebatkar', 'mûçe', 'çandinî', 'pîşesazî', 'enflasyon', 'danûstandin', 'bac', 'bazirganiya navneteweyî'] },
    ],
  },
  {
    id: 'unit48', levelId: 'level5', order: 48,
    title: 'Mafên Mirovan', description: 'C1 seviye içerik', icon: '⚖️',
    city: 'Pîranşar — İran-Irak sınırı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Mafên Bingehîn', words: ['maf', 'mafên mirovan', 'mafê jiyanê', 'rûmet', 'ewlekarî', 'parastin', 'bingehîn', 'hemûyan'] },
      { title: 'Azadî û Wekhevî', words: ['azadî', 'wekhevî', 'cihêkarî', 'rêzgirtin', 'berpirsiyarî', 'hevgirtî', 'aştî', 'qebûlkirin'] },
      { title: 'Dad û Hiqûq', words: ['dad', 'hiqûq', 'dadgeh', 'qanûn', 'dadwer', 'parêzer', 'bêgunehî', 'biryar'] },
      { title: 'Mafên Zarokan', words: ['mafên zarokan', 'zarok', 'xwendin', 'lîstin', 'tengezarî', 'xwedîkirin', 'hêvî', 'evîn'] },
      { title: 'Karma Maf', words: ['penaber', 'koçberî', 'ziman', 'çand', 'perwerde', 'tenduristî', 'welatî', 'rastî'] },
    ],
  },
  {
    id: 'unit49', levelId: 'level5', order: 49,
    title: 'Zanist û Keşif', description: 'C1 seviye içerik', icon: '🔬',
    city: 'Qorveh — Güney Kürdistan platosu',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Zanist û Lêkolîn', words: ['zanist', 'zanyar', 'lêkolîn', 'ezmûn', 'encam', 'teorî', 'delîl', 'rastî'] },
      { title: 'Fîzîk û Kîmya', words: ['fîzîk', 'kîmya', 'enerjî', 'madde', 'germahî', 'ronahî', 'atom', 'guhertin'] },
      { title: 'Biyolojî û Jiyan', words: ['biyolojî', 'hucre', 'zindî', 'pêşkeftin', 'xweza', 'jîngeh', 'parastin', 'jiyan'] },
      { title: 'Keşif û Vedîtin', words: ['vedîtin', 'îcat', 'pêşveçûn', 'teknolojî', 'serdema nû', 'gerdûn', 'feza', 'amûr'] },
      { title: 'Karma Zanist', words: ['matematîk', 'astronomî', 'jêhatî', 'pispor', 'zanageh', 'laboratûwar', 'stêrk', 'gerstêrk'] },
    ],
  },
  {
    id: 'unit50', levelId: 'level5', order: 50,
    title: 'Dengbêjî û Vegotin', description: 'C1 seviye içerik', icon: '🎵',
    city: 'Merîwan — Zêbar gölü',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Dengbêjî û Stran', words: ['dengbêj', 'stran', 'kilam', 'deng', 'lawik', 'makam', 'awaz', 'guhdar'] },
      { title: 'Çîrok û Mêjûya Devkî', words: ['çîrok', 'çîrokvan', 'efsane', 'bîranîn', 'mêjûya devkî', 'vegêran', 'berhevkirin', 'nifş'] },
      { title: 'Helbest û Wêje', words: ['helbest', 'helbestvan', 'wêje', 'nivîskar', 'wateya kûr', 'rîtm', 'xeyal', 'beyt'] },
      { title: 'Gotin û Şehrezayî', words: ['gotina pêşiyan', 'şehrezayî', 'nesîhet', 'mînak', 'watedar', 'kevneşopî', 'hikmet', 'qedir'] },
      { title: 'Karma Vegotin', words: ['mîras', 'çandî', 'zimanê dayikê', 'jiyandin', 'parastin', 'veguheztin', 'nasname', 'bîr û bawerî'] },
    ],
  },

  // ─── SEVİYE 6 — C2 ───
  {
    id: 'unit51', levelId: 'level6', order: 51,
    title: 'Hiqûq û Edalet', description: 'C2 seviye içerik', icon: '⚖️',
    city: 'Dersim/Tunceli — Munzur vadisi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Hiqûq û Mahkeme', words: ['hiqûq', 'dadgeh', 'dadwer', 'parêzer', 'dadmend', 'biryar'] },
      { title: 'Sûc û Ceza', words: ['sûc', 'ceza', 'girtîgeh', 'tawanbar', 'delîl', 'serbest man'] },
      { title: 'Maf û Azadî', words: ['maf', 'azadî', 'wekhevî', 'demokrasî', 'destûr', 'mafê dengdanê'] },
      { title: 'Dezgehên Dewletê', words: ['hukûmet', 'parleman', 'wezaret', 'serokatî', 'şaredarî', 'yasasaz'] },
      { title: 'Karma Hiqûq', words: ['qanûn', 'edalet', 'polîs', 'savcî', 'dadperwerî', 'mafdar'] },
    ],
  },
  {
    id: 'unit52', levelId: 'level6', order: 52,
    title: 'Perwerde û Zanîngeh', description: 'C2 seviye içerik', icon: '🎓',
    city: 'Bingöl — Genç ilçesi ve Peri çayı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Dibistan û Xwendin', words: ['dibistan', 'perwerde', 'ders', 'sinif', 'kitêb', 'dîktê'] },
      { title: 'Zanîngeh û Zanist', words: ['zanîngeh', 'zanist', 'lêkolîn', 'doktor', 'dîploma', 'teza'] },
      { title: 'Mamosta û Xwendekar', words: ['mamosta', 'xwendekar', 'profesor', 'fêrkirin', 'fêrbûn', 'mezûniyet'] },
      { title: 'Sîstema Perwerdeyê', words: ['xwendina seretayî', 'lîse', 'nîşan', 'sînava', 'bursa', 'perwerdekar'] },
      { title: 'Karma Perwerde', words: ['zanîn', 'huner', 'zimannasî', 'matematîk', 'mêjûnasî', 'bijîjkî'] },
    ],
  },
  {
    id: 'unit53', levelId: 'level6', order: 53,
    title: 'Mafê Jinan', description: 'C2 seviye içerik', icon: '👩‍🦱',
    city: 'Sason — Batman dağları',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Mafê Jinan', words: ['jin', 'mafê jinan', 'azadiya jinê', 'femînîzm', 'jinebûn', 'serkevtî'] },
      { title: 'Wekheviya Zayendî', words: ['zayend', 'wekheviya zayendî', 'cûdakarî', 'sexsîyet', 'mafdar bûn', 'hevdem'] },
      { title: 'Jinên Kurd di Dîrokê', words: ['şervanên jin', 'serokatiya jinê', 'malbata kurd', 'dengê jinan', 'rola jinê', 'kurêhatî'] },
      { title: 'Tundiya Zayendî', words: ['tundî', 'parastî', 'sîwaneke', 'şikandina mafan', 'têkoşîn', 'piştgirî'] },
      { title: 'Karma Mafên Jinan', words: ['bijartina jinê', 'pêşketî', 'hevbeşî', 'civata wekhev', 'jinek serbilind', 'jin û mêr'] },
    ],
  },
  {
    id: 'unit54', levelId: 'level6', order: 54,
    title: 'Tenduristiya Giyanî', description: 'C2 seviye içerik', icon: '🧘‍♀️',
    city: 'Kozluk — Batman vadisi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Tenduristiya Giyanî', words: ['tenduristiya giyanî', 'giyân', 'sihet', 'seqet', 'bêhêvî', 'aramî'] },
      { title: 'Hest û Rewş', words: ['kêfxweş', 'dilgiran', 'fikar', 'hêrs', 'bitirs', 'dilşad'] },
      { title: 'Stres û Xemgînî', words: ['stres', 'depresyon', 'xemgînî', 'westandin', 'bêxewî', 'dilxwazî'] },
      { title: 'Alîkarî û Derman', words: ['pisîkoloj', 'terapî', 'piştgiriya giyanî', 'daxwaz kirin', 'baştir bûn', 'hêvî'] },
      { title: 'Karma Tenduristî', words: ['bihîstin', 'axaftin', 'bawerî', 'kevneşopiya tedawiyê', 'tenduristiya laşî', 'derûnî'] },
    ],
  },
  {
    id: 'unit55', levelId: 'level6', order: 55,
    title: 'Çandinî û Gund', description: 'C2 seviye içerik', icon: '🌾',
    city: 'Siverek — Karacadağ etekleri',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Çandinî û Zevî', words: ['çandinî', 'zevî', 'cotkar', 'cotkirî', 'dexl', 'çîçek'] },
      { title: 'Gund û Gundiyan', words: ['gund', 'gundiyan', 'mêrg', 'kanî', 'koç', 'gir'] },
      { title: 'Ajal û Dewaran', words: ['dewar', 'mî', 'bizin', 'hesp', 'çêlekvanî', 'çêlek'] },
      { title: 'Demsalên Çandiniyê', words: ['biharê', 'çînandin', 'tovdan', 'av dan', 'berhema zivistanê', 'xirman'] },
      { title: 'Karma Jiyana Gundî', words: ['ax', 'avdêr', 'bajêr', 'pêşiya gund', 'daristanî', 'xwedaniya axê'] },
    ],
  },
  {
    id: 'unit56', levelId: 'level6', order: 56,
    title: 'Diyaspora û Koçberî', description: 'C2 seviye içerik', icon: '✈️',
    city: 'Hilvan — Gabar dağı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Koçberî û Diyaspora', words: ['koçber', 'diyaspora', 'koçberî', 'sînor', 'rizgarî', 'welatparêz'] },
      { title: 'Welat û Penaberî', words: ['welat', 'penaber', 'penaberî', 'dûrketina welatê', 'mêvandar', 'bîranîn'] },
      { title: 'Nasnama û Kok', words: ['nasnama', 'kok', 'zimanê dayikê', 'kevneşopî', 'çand', 'kurdayetî'] },
      { title: 'Jiyana Diyasporayê', words: ['yekxistî', 'vegerîn', 'hêvî', 'têkoşîn', 'bêwelat', 'rêxistîn'] },
      { title: 'Karma Diyaspora', words: ['derd', 'kêmasî', 'hemdem', 'yekîtî', 'mafê vegerînê', 'cîhana nû'] },
    ],
  },
  {
    id: 'unit57', levelId: 'level6', order: 57,
    title: 'Ekolojî û Klîma', description: 'C2 seviye içerik', icon: '🌱',
    city: 'Eruh — Siirt dağları',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Ekolojî û Xweza', words: ['ekolojî', 'hawirdor', 'xweza', 'çem', 'daristân', 'cîhanbûn'] },
      { title: 'Guhertina Avhewayê', words: ['guhertina avhewayê', 'germbûna cîhanê', 'avhewa', 'bahoza', 'zuwa', 'guheztin'] },
      { title: 'Hawirdorparêzî', words: ['hawirdorparêzî', 'parêztin', 'qirêjkirin', 'çopkirin', 'vejîn', 'xwezaparêz'] },
      { title: 'Enerjiya Xwezayî', words: ['enerjiya xwezayî', 'enerjiya tavê', 'enerjiya bayê', 'elektrîk', 'sotemenî', 'karbondiyoksît'] },
      { title: 'Karma Ekolojî', words: ['cûrbecûrî', 'avjeniya çeman', 'daristan birîn', 'paqijî', 'ava vexwarinê', 'heywanên xeterdar'] },
    ],
  },
  {
    id: 'unit58', levelId: 'level6', order: 58,
    title: 'Ziman û Nasname', description: 'C2 seviye içerik', icon: '🗣️',
    city: 'Pervari — Botan çayı kıyısı',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Zimanê Kurdî', words: ['ziman', 'kurmancî', 'alfabeya kurdî', 'zimanzanî', 'peyv', 'rêziman', 'devok', 'zimanê dayikê'] },
      { title: 'Zaravaên Kurdî', words: ['zaravaên kurdî', 'soranî', 'zazakî', 'goranî', 'ferq', 'hevpar', 'cihêreng', 'têgihiştin'] },
      { title: 'Nasnama Kurdî', words: ['nasname', 'nasnama kurdî', 'netewe', 'çand', 'bîranîn', 'mîras', 'wekhevî', 'azadî'] },
      { title: 'Welat û Kok', words: ['welat', 'kurdistan', 'kok', 'cografya', 'sînor', 'welatparêzî', 'dûrî û nêzîkî', 'xakê xwe'] },
      { title: 'Ziman û Çand', words: ['folklor', 'kilam', 'çîrok', 'şiir', 'nivîskar', 'wêje', 'veguheztin', 'jiyana çandî'] },
    ],
  },
  {
    id: 'unit59', levelId: 'level6', order: 59,
    title: 'Gotinên Pêşiyan', description: 'C2 seviye içerik', icon: '📜',
    city: 'Beytüşşebap — Hakkari derin vadileri',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Gotinên Pêşiyan', words: ['gotina pêşiyan', 'biwêj', 'hikmeta', 'mêze bike', 'wate', 'nimûne', 'şehrezayî', 'ji dil tê'] },
      { title: 'Biwêjên Jiyanê', words: ['ji dil kirin', 'serê xwe xwarinê', 'bi çavan dîtin', 'lingên xwe rakirin', 'devê xwe girtin', 'dilê xwe rakirin', 'çavên xwe vekirin', 'riya xwe girtin'] },
      { title: 'Bêjeyên Wênedar', words: ['wek şêr', 'wek av', 'wek kevirek', 'dil wek gul', 'wek bayê havînê', 'serê wek çiyayê', 'deng wek bilbil', 'çav wek stêrk'] },
      { title: 'Hîkmetên Kurdî', words: ['zane', 'şirêt', 'rêz', 'dilovanî', 'xemxwarî', 'qedirbilêz', 'saxlem', 'bi xêr û ber'] },
      { title: 'Karma Biwêj', words: ['pêşkêş kirin', 'zanistî', 'ji bîr kirin', 'bîranîn', 'vegotin', 'tê gihiştin', 'kûr', 'dewlemendî'] },
    ],
  },
  {
    id: 'unit60', levelId: 'level6', order: 60,
    title: 'Serbilindî û Pêşeroj', description: 'C2 seviye içerik', icon: '🦅',
    city: 'Uludere/Roboski — sınır geçidi',
    culturalHint: 'İleri seviye kültürel ve dil bağlamı — Baran, Berfin ve Kurdo ile devam ediyor.',
    lessons: [
      { title: 'Serbilindiya Kurdî', words: ['serbilindî', 'serbilind', 'azadî', 'maf', 'bîr û bawerî', 'xwebûn', 'wêrek', 'serxwebûn'] },
      { title: 'Pêşeroja Zimên', words: ['pêşeroj', 'nifş', 'veguheztin', 'parastin', 'zindî kirin', 'pêşveçûn', 'hêvî', 'berpirsiyarî'] },
      { title: 'Kultura Zindî', words: ['kultura zindî', 'govend', 'stranbêj', 'cil û berg', 'xwarinên kevnar', 'hunermend', 'çandî', 'mîras'] },
      { title: 'Bangawaziya Ziman', words: ['bangawaz', 'hînkirin', 'belavkirin', 'hevpar', 'civat', 'têkilî', 'piştgirî', 'pêkve'] },
      { title: 'Xatimekirin', words: ['xatimekirin', 'serkeftin', 'spasî', 'bijî', 'rêwîtî', 'destpêk', 'berdewam', 'serkeftî'] },
    ],
  },
];
